# Generated by Django 5.0.2 on 2024-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='imgurl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
