# Generated by Django 5.0.2 on 2024-02-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_imgurl_portfolioitem_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
